# Use root/example as user/password credentials

services:

  db:
    image: mariadb:10.6-jammy
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: skydev
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
